### PR TITLE
2 fa auth

### PR DESCRIPTION
**Pull request by avan-dam**
Thanks :)

### CODE REVIEW

**Comment by Alpha1337k** [comment]
Hi the linter fails. Plz fix

**Review by harou24 — CHANGES_REQUESTED** [review]
It needs to be refactored and cleaned up. 2FA should be in  a separate module that we could call from Register component. Think more like doing reusable independent components with one single responsibility.
Exemple : you have chat that is composed of chat side bar and chat box, but each one of them is independent.

**Comment by avan-dam** [comment]
I am aware that one of the linter fails because constructor empty for the protector. Still please check the work i have done with the flow for 2FA. If happy please approve because then a lot easier to work with rubens.

**Comment by Alpha1337k** [comment]
Looks good, fixes will be fixed

**Pull request merged**
